---
functional:
  - Пользователь может регистрироваться. 2.1
  - Для регистрации пользователь прописывает Nikname, email, password. 2.1.1
  - Nikname должен содержать минимум 3 символа, символа русского/английского языка. 2.1.2
  - Email для регистрации должен быть действительным и корректным. 2.1.3
  - Password должен содержать не менее 6 символов русского, англисйкого языка или спецсимволов. 2.1.4
  - Нельзя зарегестрироваться 2 раза на один email. 2.1.5
  - Зарегистрированный пользователь может восстановить забытый пароль по email. 2.1.6
  - Пользователь может авторизоваться для входа в приложение. 2.2 (Далее в требованиях Авторизованный пользователь будет называться - пользователь).
  - Пользователь может авторизоваться по email и password. 2.2.1
  - Пользователь может авторизоваться с помощью аккаунта GitHub. 2.2.2
  - Пользователь может авторизоваться с помощью аккаунта Discord. 2.2.3
  - Ошибка "EMAIL_NOT_FOUND" отображена при вводе незарегистрированного email и попытке авторизации. 2.2.4
  - Ошибка "INVALID_PASSWORD" отображена при вводе зарегистрированного email и неверного пароля, при попытке авторизации. 2.2.5
  - Ошибка "Email required" отображена при незаполненном поле email и попытке авторизации. 2.2.6
  - Ошибка "Password required" отображена при назаполненном поле password и попытке авторизации. 2.2.7
  - Ошибка "Invalid email" отображена при недействительнои и некорректном Email при попытке регистрации/авторизации. 2.2.8
  - Пользователь может просматривать свой профиль. 2.3
  - Пользователю доступна настроек. 2.3.1
  - Пользователь может менять свой Nikname. 2.3.2
  - Пользователь может выйти из аккаунта. 2.3.6
  - Пользователь может просматривать раздел лобби на главной странице. 2.3.8
  - Пользователь может просматривать раздел турниры на главной странице. 2.3.9
  - Пользователь может просматривать раздел список завершенных игр на главной странице. 2.3.7
  - Пользователь может просматривать таблицу лидеров на главной странице. 2.3.10
  - Пользователь может создавать игру. 2.3.11
  - Пользователь может изменять настройки в разделе создания игры. 2.3.12
  - Пользователь может принять приглашение в игру от другого авторизированного пользователя. 2.3.13
  - Пользователь может отклонить приглашение в игру от другого авторизированного пользователя. 2.3.14
  - Пользователю доступно меню. 2.3.15
  - Пользователю доступна страница своего профиля. 2.3.16
  - Пользователю доступна страница настройки. 2.3.17
  - Пользователю доступна страница рейтинг пользователей. 2.3.18
  - Пользователю доступна страница задания. 2.3.19
  - Пользователь может просматривать задания. 2.3.20
  - Пользователь может создавать задания. 2.3.21
  - Пользователю доступна страница сборник заданий 2.3.22
  - Пользователь может просматривать сборник заданий. 2.3.23
  - Пользователь может создавать сборники заданий. 2.3.24
  - Пользователь доступна страница турниры. 2.3.25
  - Пользователь может просматривать список турниров. 2.3.26
  - Пользователь может создавать турниры. 2.3.27
  - Пользователь может отправлять и принимать сообщения во всех чатах приложения. 2.3.28
  - Пользователь может просматривать историю игры нажатием кнопки "Open History" 2.3.29
  - Пользователь может просматривать историю игр других пользователей в разделе "COMPLETED GAMES". 2.3.30
  - Пользователь может просматривать историю своих игр в разделе "COMPLETED GAMES" на странице "My profile". 2.3.31
  - Пользователю доступен проигрыватель при просмотре истории игры. 2.3.32
  - Пользователю доступны настройки проигрывателя при просмотре игры. 2.3.33
  - Пользователь может скопировать ссылку истории игры при просмотре. 2.3.34
  - После победы в игре пользователю показывается победное модальное окно. 2.3.35
  - За победу пользователю начисляются очки. 2.3.36
  - Незарегистрированный пользователь может принять участие в игре с ботом. 2.4
  - Незарегистрированный пользователь в игре отображен под ником John Doe. 2.4.1
  - Незарегистрированный пользователь может просматривать историю своей игры с ботом. 2.4.2
  - Незарегистрированный пользователь может пользоваться чатом в игре с ботом. 2.4.3
  - Незарегистрированный пользователь не может авторизоваться по email и password. 2.4.4
  - Незарегистрированный пользователь может просматривать "Guide" в игре с ботом. 2.4.5
  - Приложение состоит из разделов - "lobby", "users", "settings", "tasks", "tasks_pack", "tournaments", "games". 2.5  
  - Контент приложения должен отображаться корректно и без орфографических/грамматических ошибок. 2.5.1
  - Корректное отображение и функционал элементов интерфейса. 2.5.2
non-functional:
  - Сайт должен быть безопасным и защищать данные пользователя. 1
  - Сайт должен быть разработан с учетом удобства использования и оптимизирован для скорости работы. 1.1
  - Сайт должен быть удобным на мобильном устройстве. 1.2
  - Сайт должен быть протестирован на совместимость с последними версиями браузеров. 1.3
  - Сайт должен быть способен обрабатывать большое количество трафика. 1.4
implicit:
  - Поисковая строка в разделе "Create a game" - "Game type" - "With a friend" показывает более релевантные данные по мере заполнения текста. 2.5
  - Tooltip сообщение кнопки "Invite" должно появляться при нажатии на кнопку. 2.5
  - Tooltip сообщение кнопки "Invite" должно скрываться при отведении курсора с кнопки или tooltip сообщения. 2.5
  - Сообщения и Nickname пользователей должны быть корректно отображены в окне чата. 2.5
  - Сообщения отправляются путем написания текста в текстовое поле чата и нажатии кнопки клавиатуры "Enter"/нажатия на кнопку чата "Send". 2.5
  - При нажатии на кнопку "Emoji" пользователь может нажать нужный смайл для перемещения его в текстовое поле чата и последующей отправки в чат. 2.5
 
