---
functional:
  - Пользователь может регистрироваться. 2.1
  - Зарегистрированный пользователь может удалить свой аккаунт. 2.1.1
  - Для регистрации пользователь прописывает Nikname, email, password. 2.1.2
  - Nikname должен содержать минимум 1 символ русского или английского языка. 2.1.3
  - Email должен содержать только символы английского языка и спецсимволы. 2.1.4
  - Password должен содержать не менее 6 символов русского, англисйкого языка или спецсимволов. 2.1.5
  - Нельзя зарегестрироваться 2 раза на один email. 2.1.6
  - Зарегистрированный пользователь может восстановить забытый пароль по email. 2.1.7
  - Пользователь может авторизоваться для входа в приложение. 2.2 (Далее в требованиях Авторизованный пользователь будет называться - пользователь).
  - Пользователь может авторизоваться по email и password. 2.2.1
  - Пользователь может авторизоваться с помощью аккаунта GitHub. 2.2.2
  - Пользователь может авторизоваться с помощью аккаунта Discord. 2.2.3
  - Ошибка "EMAIL_NOT_FOUND" отображена при вводе незарегистрированного email и попытке авторизации. 2.2.4
  - Ошибка "INVALID_PASSWORD" отображена при вводе зарегистрированного email и неверного пароля, при попытке авторизации. 2.2.5
  - Ошибка "Email required" отображена при незаполненном поле email и попытке авторизации. 2.2.6
  - Ошибка "Password required" отображена при назаполненном поле password и попытке авторизации. 2.2.7
  - Пользователь может просматривать свой профиль. 2.3
  - Пользователю доступна настроек. 2.3.1
  - Пользователь может менять свой Nikname. 2.3.2
  - Пользователь может выйти из аккаунта. 2.3.6
  - Пользователь может просматривать раздел лобби на главной странице. 2.3.8
  - Пользователь может просматривать раздел турниры на главной странице. 2.3.9
  - Пользователь может просматривать раздел список завершенных игр на главной странице. 2.3.7
  - Пользователь может просматривать таблицу лидеров на главной странице. 2.3.10
  - Пользователь может создавать игру. 2.3.11
  - Пользователь может изменять настройки в разделе создания игры. 2.3.12
  - Пользователь может принять приглашение в игру от другого авторизированного пользователя. 2.3.13
  - Пользователь может отклонить приглашение в игру от другого авторизированного пользователя. 2.3.14
  - Пользователю доступно меню. 2.3.15
  - Пользователю доступна страница своего профиля. 2.3.16
  - Пользователю доступна страница настройки. 2.3.17
  - Пользователю доступна страница рейтинг пользователей. 2.3.18
  - Пользователю доступна страница задания. 2.3.19
  - Пользователь может просматривать задания. 2.3.20
  - Пользователь может создавать задания. 2.3.21
  - Пользователю доступна страница сборник заданий 2.3.22
  - Пользователь может просматривать сборник заданий. 2.3.23
  - Пользователь может создавать сборники заданий. 2.3.24
  - Пользователь доступна страница турниры. 2.3.25
  - Пользователь может просматривать список турниров. 2.3.26
  - Пользователь может создавать турниры. 2.3.27
  - Незарегистрированный пользователь может принять участие в игре с ботом. 2.4
  - Незарегистрированный пользователь в игре отображен под ником John Doe. 2.4.1
  - Незарегистрированный пользователь может просматривать историю своей игры с ботом. 2.4.2
  - Незарегистрированный пользователь может пользоваться чатом в игре с ботом. 2.4.3
  - Незарегистрированный пользователь не может авторизоваться по email и password. 2.4.4
non-functional:
  - Сайт должен быть безопасным и защищать данные пользователя. 1
  - Сайт должен быть разработан с учетом удобства использования и оптимизирован для скорости работы. 1.1
  - Сайт должен быть удобным на мобильном устройстве. 1.2
  - Сайт должен быть протестирован на совместимость с последними версиями браузеров. 1.3
  - Сайт должен быть способен обрабатывать большое количество трафика. 1.4
implicit:
  - 
 
