---
functional:
  -

  - 
non-functional:
  - Сайт должен быть безопасным и защищать данные пользователя. 1
  - Сайт должен быть разработан с учетом удобства использования и оптимизирован для скорости работы
  - Сайт должен быть удобным на мобильном устройстве
  - Сайт должен быть протестирован на совместимость с последними версиями браузеров
  - Сайт должен быть способен обрабатывать большое количество трафика
implicit:
  - Язык применяемый для создания тестов к играм "Clojure"
  - Язык применяемый в бэкэнд(серверная сторона) "Elixir"
  - Фреймворк "Phoenix", написанный на языке "Elixir"
  - Язык применяемый для фронтэнд "JS" (React, Redux)
  - "Ansible" автоматизирует развёртку среды для разработчика
  
  
  - Пользователь может регистрироваться. 2.1
  - Зарегистрированный пользователь может удалить свой аккаунт. 2.1.1
  - Для регистрации пользователь прописывает Nikname, email, password. 2.1.2
  - Nikname должен содержать минимум 1 символ русского или английского языка. 2.1.3
  - Email должен содержать только символы английского языка и спецсимволы. 2.1.4
  - Password должен содержать не менее 6 символов русского, англисйкого языка или спецсимволов. 2.1.5
  - Нельзя зарегестрироваться 2 раза на один email. 2.1.6
  
  - Пользователь может авторизоваться для входа в приложение. 2.2
  - Пользователь может авторизоваться с помощью аккаунта GitHub. 2.2.1
  - Пользователь может авторизоваться с помощью аккаунта Discord. 2.2.2
  
  - Зарегистрированный пользователь может просматривать свой профиль. 2.3
  - Зарегистрированному пользователю доступны настройки. 2.3.1
  - Зарегистрированный пользователь может менять свой Nikname. 2.3.2
  - Зарегистрированный пользователь может выйти из аккаунта. 2.3.6
  - 
  
  - Пользователь принять участие в игре без регистрации и авторизации.
  - 
  
  ВОЗМОЖНЫЕ ТРЕБОВАНИЯ:
  - Зарегистрированный пользователь можеть менять свой password. 2.3.3
  - Зарегистрированный пользователь можеть менять свой email. 2.3.4
  - Зарегистрированный пользователь можеть менять свой аватар. 2.3.5
 
