---
functional:
  - Сайт должен быть безопасным и защищать данные пользователя
  - 
non-functional:
  - Сайт должен быть разработан с учетом удобства использования и оптимизирован для скорости работы
  - Сайт должен быть удобным на мобильном устройстве
  - Сайт должен быть протестирован на совместимость с последними версиями браузеров
  - Сайт должен быть способен обрабатывать большое количество трафика
implicit:
  - Язык применяемый для создания тестов к играм "Clojure"
  - Язык применяемый в бэкэнд(серверная сторона) "Elixir"
  - Фреймворк "Phoenix", написанный на языке "Elixir"
  - Язык применяемый для фронтэнд "JS" (React, Redux)
  - "Ansible" автоматизирует развёртку среды для разработчика
