---
  - Nickname должен содержать минимум 3 символа, символа русского/английского языка. 2.
  - Nickname должен быть уникальным. 2.1
  - Email для регистрации должен быть действительным и корректным. 2.2
  - Password должен содержать не менее 6 символов русского, англисйкого языка или спецсимволов. 2.3
  - Нельзя зарегестрироваться 2 раза на один email. 2.4
  - Зарегистрированный пользователь может восстановить забытый пароль по email. 2.5
  - Пользователь может авторизоваться для входа в приложение. 3 (Далее в требованиях Авторизованный пользователь будет называться - пользователь).
  - Пользователь может авторизоваться по email и password. 3.1
  - Пользователь может авторизоваться с помощью аккаунта GitHub. 3.2
  - Пользователь может авторизоваться с помощью аккаунта Discord. 3.3
  - Ошибка "EMAIL_NOT_FOUND" отображена при вводе незарегистрированного email и попытке авторизации. 4
  - Ошибка "INVALID_PASSWORD" отображена при вводе зарегистрированного email и неверного пароля, при попытке авторизации. 4.1
  - Ошибка "Email required" отображена при незаполненном поле email и попытке авторизации. 4.2
  - Ошибка "Password required" отображена при назаполненном поле password и попытке авторизации. 4.3
  - Ошибка "Invalid email" отображена при недействительнои и некорректном Email при попытке регистрации/авторизации. 4.4
  - Ошибка "already_in_a_game" отображена при попытке начать игру во время участия в другой игре. 4.5
  - Пользователь может просматривать раздел лобби на главной странице. 5
  - Пользователь может просматривать раздел турниры на главной странице. 5.1
  - Пользователь может просматривать раздел список завершенных игр на главной странице. 5.2
  - Пользователь может просматривать таблицу лидеров на главной странице. 5.3
  - Пользователь может создавать игру. 6
  - Пользователь может изменять настройки в разделе создания игры. 6.1
  - Пользователь может выбирать "level" при создании игры. 6.1.1
  - Пользователю доступны 4 уровня игры. 6.1.2
  - Пользователь может выбирать "Game type" при создании игры. 6.1.3
  - Пользователю доступен "Game type" - "with other users". 6.1.4
  - Пользователю доступен "Game type" - "with a friend". 6.1.5
  - Пользователю достпуна поисковая строка "Choose opponent" при создании игры с "Game type" - "with a friend". 6.1.6
  - Пользователю доступен "Game type" - "with a bot". 6.1.7
  - Пользователю доступен выбор "Time control" при создании игры. 6.1.7
  - Пользователю доступен "Time control" от 3 до 60 минут. 6.1.8
  - Пользователю доступен выбор задания по "name". 6.1.9
  - Пользователю доступен выбор задания по "tags". 6.1.10
  - Пользователь может принять приглашение в игру от другого авторизированного пользователя. 6.2
  - Пользователь может отклонить приглашение в игру от другого авторизированного пользователя. 6.2.1
  - Пользователь может отправлять приглашение в игру другому авторизированному пользователю. 6.2.2
  - Пользователю доступно меню. 7.
  - Пользователь может выйти из аккаунта. 7.1
  - Пользователю доступна страница своего профиля. 7.2
  - Пользователю доступна страница настройки. 7.3
  - Пользователь может менять свой Nickname. 7.3.1
  - Пользователь может менять "your weapon" язык программирования. 7.3.2
  - Пользователь может менять "sound type". 7.3.2
  - Пользователь может выбрать "sound type" из "dendy/cs/standart/silent". 7.3.4
  - Пользователю доступен ползунок "sound level". 7.3.5
  - Пользователю доступна привязка аккаунта к "github/discord". 7.3.6
  - Пользователю доступна страница рейтинг пользователей. 7.4
  - Рейтинг пользователей разделен на "weekly/monthly/total". 7.4.1
  - Пользователю доступна поисковая строка "username" для поиска пользователей в "user rating". 7.4.2
  - Таблица "user rating" может быть отсортирована по "rank/user/rating/games played/perfomance/joined". 7.4.3
  - В таблице есть checkbox "with bot" для выбора отображения таблицы с ботами/без ботов. 7.4.4
  - В таблице есть кнопка ссылка на "github" пользователя. 7.4.5
  - Пользователю доступна страница задания. 7.5 
  - Пользователь может просматривать задания. 7.5.1
  - Пользователь может создавать задания. 7.5.2
  - "Name" задания должен быть уникальным. 7.5.3
  - При создании задания пользователю доступен выбор уровня задания от 1 до 4. 7.5.4
  - При создании задания пользователю доступен выбор видимости задания "hidden/public". 7.5.5
  - Пользователь может редактировать созданные задания. 7.5.6
  - Пользователю доступна страница сборник заданий. 7.6
  - Пользователь может просматривать сборник заданий. 7.6.1
  - Пользователь может создавать сборники заданий. 7.6.2
  - "Name" сборника заданий должно быть уникальным. 7.6.3
  - При создании сборника заданий доступен выбор видимости сборника "hidden/public". 7.6.4
  - Пользователь может редактировать созданные сборники заданий. 7.6.5
  - Пользователь доступна страница турниры. 7.7
  - Пользователь может просматривать список турниров. 7.7.1
  - У турниров в списке отображены "state" - "upcoming/active/finished". 7.7.2
  - Пользователь может вступать в турниры, со статусом "upcoming". 7.7.3
  - Пользователь может просматривать турниры, со статусом "upcoming/active/finished". 7.7.4
  - Пользователь может создавать турниры. 7.7.5
  - Пользователь создавший турнир может удалить турнир. 7.7.6
  - Пользователь создавший турнир может выгонять других пользователей. 7.7.7
  - Пользователь создавший турнир может банить пользователей в чате турнира. 7.7.8
  - Пользователь создавший турнир может очищать список банов в чате турнира. 7.7.9
  - Пользователь создавший закрытый турнир может сделать его открытм 7.7.10
  - Закрытый турнир виден только пользователям участвующим в нем, а так же пользователю создавшему его. 7.7.11
  - Пользователь может покидать турниры. 7.7.12
  - Турниры с типом доступа "public" доступны для просмотра и участия всем пользователям. 7.7.13
  - Пользователь может отправлять и принимать сообщения во всех чатах приложения. 8
  - В "lobby" пользователям доступен общий чат. 8.1
  - В общем чате "lobby" присутствует возможность выбирать и отправлять "emoji". 8.2
  - В игре присутствует чат доступный для участников и зрителей. 8.3
  - В чате игры присутствует возможность выбирать и отправлять "emoji". 8.4
  - В турнире присутствует чат турнира. 8.5
  - Чат турнира доступен всем участникам и зрителям турнира. 8.6
  - Чат турнира также отображен в играх турнира. 8.7
  - Приватный чат турнира доступен только участникам турнира. 8.8
  - Сообщения и Nickname пользователей должны быть корректно отображены в окне чата. 8.9
  - Сообщения отправляются путем написания текста в текстовое поле чата и нажатии кнопки клавиатуры "Enter"/нажатия на кнопку чата "Send". 8.10
  - Пользователь может просматривать историю игры. 9
  - Пользователю доступен проигрыватель при просмотре истории игры. 9.1
  - Пользователю доступны настройки проигрывателя при просмотре игры. 9.2
  - Пользователь может скопировать ссылку истории игры при просмотре. 9.3
  - Незарегистрированный пользователь может принять участие в игре с ботом. 10
  - Незарегистрированный пользователь в игре отображен под ником John Doe. 10.1
  - Незарегистрированный пользователь может просматривать историю своей игры с ботом. 10.2
  - Незарегистрированный пользователь может пользоваться чатом в игре с ботом. 10.3
  - Незарегистрированный пользователь не может авторизоваться по email и password. 10.4
  - Незарегистрированный пользователь может просматривать "Guide" в игре с ботом. 10.5
  - Приложение состоит из разделов - "lobby", "users", "settings", "tasks", "tasks_pack", "tournaments", "games". 11
  - Контент приложения должен отображаться корректно и без орфографических/грамматических ошибок. 11.1
  - Корректное отображение и функционал элементов интерфейса. 11.2
  - Во время игры есть возможность выбора отображения задания и гайда на английском и русском языке. 12
  - Во время игры можно использовать текстовый редактор "Vim" 12.1
  - Во время игры есть возможность выбора темы отображения "Light"/"Dark" 12.2
  - Во время игры можно выбрать язык программирования для решения задачи. 12.3
  - Во время игры пользователю доступно игровое текстовое поле, для написания решения задачи. 12.4
  - Все строчки игрового текстового поля пронумерованы. 12.5
  - Игровое текстовое поле принимает символы русского/английского языка и спецсимволы. 12.6
  - Во время игры пользователю доступно для просмотра игровое поле противника в режиме онлайн. 12.7
  - Во время игры можно сбросить изменения игрового поля к первоначальному виду. 12.8
  - Пользователь может самостоятельно сдаться во время игры. 12.9
  - Пользователь может самостоятельно проверить свое решение. 12.10
  - Если решение задачи пользователем было неверным, то игра выдает отчет об ошибке и игра продолжается. 12.11
  - Все проверки игры и действия пользователей происходят в решиме онлайн, не прерывая игровой процесс. 12.12
  - Победа присуждается первому правильно решившему задачу пользователю. 12.12
  - За победу пользователю начисляются очки. 12.13
  - Праивльность решения задания определяет приложение. 12.14
  - После победы/поражения в игре пользователю показывается победное модальное окно. 12.15
  - После победы/поражения в игре, возможно сделать "Rematch" игры. 12.16
  - Игра завершается при победе, самостоятельной сдаче, победе проитвника, сдаче противника, завершении времени. 12.17
  - Игра завершенная по истечении времени, при выходе из нее игроков не отображается в истории завершенных игр. 12.18
  - Пользователь может во время игры переходить на другие страницы приложения с последующим возвращением в игру, до ее завершения. 12.19
  - Пользователь может во время игры выходить из приложения с последующим возвращением в игру, до ее завершения. 12.20
  - "Rematch" игры запускает новую игру с настройками предыдушей, с тем же противником. 12.21
  - Игру "Game type" = "with other users" можно отменить, до присоединения к ней противника. 12.22
  - Отправленное приглашение в игру можно отменить, до принятия противником. 12.23
  - Пользователю доступна отбравка обратной связи в окно "Send feedback" в "Slack" сообщество разработчиков. 12.25
  - Окно обратной связи разделено на 3 категории - "Bug"/"Improvement"/"Feature". 12.26
non-functional:
  - Сайт должен быть безопасным и защищать данные пользователя. 1
  - Сайт должен быть разработан с учетом удобства использования и оптимизирован для скорости работы. 1.1
  - Сайт должен быть удобным на мобильном устройстве. 1.2
  - Сайт должен быть протестирован на совместимость с последними версиями браузеров. 1.3
  - Сайт должен быть способен обрабатывать большое количество трафика. 1.4
implicit:
  - Туринры с типом доступа "token" доступны для просмотра и участия только приглашенным пользователям. 7.7.14
  - Турнир нельзя создавать с прошедшей датой начала турнира. 7.7.15
  - Пользователь может принимать участие одновременно только в одной игре. 12.24
  - Поисковая строка в разделе "Create a game" - "Game type" - "With a friend" показывает более релевантные данные по мере заполнения текста.
  - Tooltip сообщение кнопки "Invite" должно появляться при нажатии на кнопку. 
  - Tooltip сообщение кнопки "Invite" должно скрываться при отведении курсора с кнопки или tooltip сообщения.
